/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue.gestionnaire;

import gestion.Authentification.AbstractDAO;
import gestion.Authentification.Connexion;
import gestion.Authentification.DAO;
import gestion.Authentification.Gestionnaire;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import vue.IVue;
import vue.article.Button;
import vue.article.ButtonRenderer;
import vue.article.TModel;

/**
 *
 * @author VEK
 */
public class ListeGestionnaire extends javax.swing.JPanel implements IVue {
    private ArrayList<ArrayList<Object>> data;
    private ArrayList<String> title= new ArrayList<String>();
    TModel modele;
    Connection con = Connexion.getConnection();
    private boolean Admin=false;
    private int IDgest=0;
    /**
     * Creates new form Actuel
     */
    public ListeGestionnaire(boolean ad,int gestion) {
        initComponents();
        buttonGroup1.add(jRadioButton_F);
        buttonGroup1.add(jRadioButton_M);
        
        Admin=ad;
        IDgest=gestion;
        title.add("Id");
        title.add("Nom");
        title.add("Prenom");
        title.add("Sexe");
        title.add("Adresse");
        title.add("Telephone");
        title.add("Suppression");
        jTextField_nom.setVisible(false);
        jTextField_pre.setVisible(false);
        jTextField_adresse.setVisible(false);
        jTextField_tel.setVisible(false);
        jRadioButton_M.setVisible(false);
        jRadioButton_F.setVisible(false);
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
            DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
            data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:gestdao.recuperer()){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele=new TModel(data, title);
            tableau.setModel(modele);
            tableau.getColumn("Suppression").setCellRenderer(new ButtonRenderer()); 
            tableau.getColumn("Suppression").setCellEditor(new ButtonSuppEditorGest(new JCheckBox(),Admin,IDgest));
            
    }
     @Override
    public void afficher() {
        this.setVisible(true);
    }

    @Override
    public void cacher() {
        this.hide();
    }
    public void affichageNom(){
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
            data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:gestdao.recuperer()){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox_nom = new javax.swing.JCheckBox();
        jTextField_nom = new javax.swing.JTextField();
        jCheckBox_pre = new javax.swing.JCheckBox();
        jTextField_pre = new javax.swing.JTextField();
        jCheckBox_tel = new javax.swing.JCheckBox();
        jCheckBox_sexe = new javax.swing.JCheckBox();
        jCheckBox_adresse = new javax.swing.JCheckBox();
        jTextField_tel = new javax.swing.JTextField();
        jRadioButton_M = new javax.swing.JRadioButton();
        jRadioButton_F = new javax.swing.JRadioButton();
        jTextField_adresse = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableau.setRowHeight(25);
        tableau.setShowHorizontalLines(false);
        tableau.setShowVerticalLines(false);
        tableau.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tableau);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 967, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Type recherche :");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Recherche :");

        jCheckBox_nom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox_nom.setText("Nom");
        jCheckBox_nom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_nomItemStateChanged(evt);
            }
        });

        jTextField_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nomKeyReleased(evt);
            }
        });

        jCheckBox_pre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox_pre.setText("Prénom");
        jCheckBox_pre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_preItemStateChanged(evt);
            }
        });

        jTextField_pre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_preKeyReleased(evt);
            }
        });

        jCheckBox_tel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox_tel.setText("Telephone");
        jCheckBox_tel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_telItemStateChanged(evt);
            }
        });

        jCheckBox_sexe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox_sexe.setText("Sexe");
        jCheckBox_sexe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_sexeItemStateChanged(evt);
            }
        });

        jCheckBox_adresse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox_adresse.setText("Adresse");
        jCheckBox_adresse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_adresseItemStateChanged(evt);
            }
        });

        jTextField_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_telKeyReleased(evt);
            }
        });

        jRadioButton_M.setText("M");
        jRadioButton_M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_MItemStateChanged(evt);
            }
        });

        jRadioButton_F.setText("F");
        jRadioButton_F.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_FItemStateChanged(evt);
            }
        });
        jRadioButton_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FActionPerformed(evt);
            }
        });

        jTextField_adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_adresseActionPerformed(evt);
            }
        });
        jTextField_adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_adresseKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_nom)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_pre))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_tel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_sexe)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton_M)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_F)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_adresse))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_nom)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox_pre)
                    .addComponent(jCheckBox_tel)
                    .addComponent(jCheckBox_sexe)
                    .addComponent(jCheckBox_adresse))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton_M)
                        .addComponent(jRadioButton_F)
                        .addComponent(jTextField_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IVue vue=new Ajouter(tableau);
        vue.afficher();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox_nomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_nomItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox_nom.isSelected()){
            jTextField_nom.setVisible(true);
            jPanel2.validate();
            affichageNom();
        }
        else{
            jTextField_nom.setVisible(false);
            jPanel2.validate();
        }
            
    }//GEN-LAST:event_jCheckBox_nomItemStateChanged
    
    private boolean isNumeric(char c){
        try{
            Integer.parseInt(String.valueOf(c));
        }
        catch(NumberFormatException ex){
            return false;
        }
        return true;
    }
    
    private void jTextField_nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nomKeyReleased
        // TODO add your handling code here:
        ArrayList<Gestionnaire> tab=nom_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jTextField_nomKeyReleased

    private void jCheckBox_preItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_preItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox_pre.isSelected()){
            jTextField_pre.setVisible(true);
            jPanel2.validate();
           affichageNom();
        }
        else{
            jTextField_pre.setVisible(false);
            jPanel2.validate();
        }
            
    }//GEN-LAST:event_jCheckBox_preItemStateChanged

    private void jTextField_preKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_preKeyReleased
        ArrayList<Gestionnaire> tab=prenom_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jTextField_preKeyReleased

    private void jCheckBox_telItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_telItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox_tel.isSelected()){
            jTextField_tel.setVisible(true);
            jPanel2.validate();
            affichageNom();
        }
        else{
            jTextField_tel.setVisible(false);
            jPanel2.validate();
        }
            
    }//GEN-LAST:event_jCheckBox_telItemStateChanged

    private void jCheckBox_sexeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_sexeItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox_sexe.isSelected()){
            jRadioButton_M.setVisible(true);
            jRadioButton_F.setVisible(true);
            jPanel2.validate();
            affichageNom();
        }
        else{
            jRadioButton_M.setVisible(false);
            jRadioButton_F.setVisible(false);
            jPanel2.validate();
        }
    }//GEN-LAST:event_jCheckBox_sexeItemStateChanged

    private void jCheckBox_adresseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_adresseItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox_adresse.isSelected()){
            jTextField_adresse.setVisible(true);
           jPanel2.validate();
            affichageNom();
        }
        else{
            jTextField_adresse.setVisible(false);
            jPanel2.validate();
        }
            
    }//GEN-LAST:event_jCheckBox_adresseItemStateChanged
    
    public ArrayList<Gestionnaire> nom_selected(){
        String nom;
        nom=jTextField_nom.getText();
        Connection con=Connexion.getConnection();
        ArrayList<Gestionnaire> tab=new ArrayList<Gestionnaire>();
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
        try{
            Statement req=con.createStatement();
            ResultSet result=req.executeQuery("SELECT * FROM gestionnaire WHERE nomgest like "+" \"%"+nom+"%\"");
            while(result.next()){
                tab.add(gestdao.rechercher(result.getInt("idgest")));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        return tab;
    }
    public ArrayList<Gestionnaire> prenom_selected(){
        String prenom;
        prenom=jTextField_pre.getText();
        Connection con=Connexion.getConnection();
        ArrayList<Gestionnaire> tab=new ArrayList<Gestionnaire>();
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
        try{
            Statement req=con.createStatement();
            ResultSet result=req.executeQuery("SELECT * FROM gestionnaire WHERE prenomgest like "+" \"%"+prenom+"%\"");
            while(result.next()){
                tab.add(gestdao.rechercher(result.getInt("idgest")));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        return tab;
    }
    public ArrayList<Gestionnaire> tel_selected(){
        String tel;
        tel=jTextField_tel.getText();
        Connection con=Connexion.getConnection();
        ArrayList<Gestionnaire> tab=new ArrayList<Gestionnaire>();
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
        try{
            Statement req=con.createStatement();
            ResultSet result=req.executeQuery("SELECT * FROM gestionnaire WHERE telgest like "+" \"%"+tel+"%\"");
            while(result.next()){
                tab.add(gestdao.rechercher(result.getInt("idgest")));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        return tab;
    }
    public ArrayList<Gestionnaire> adresse_selected(){
        String adresse;
        adresse=jTextField_adresse.getText();
        Connection con=Connexion.getConnection();
        ArrayList<Gestionnaire> tab=new ArrayList<Gestionnaire>();
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
        try{
            Statement req=con.createStatement();
            ResultSet result=req.executeQuery("SELECT * FROM gestionnaire WHERE adressegest like "+" \"%"+adresse+"%\"");
            while(result.next()){
                tab.add(gestdao.rechercher(result.getInt("idgest")));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        return tab;
    }
    public ArrayList<Gestionnaire> sexe_selected(){
        String sexe;
        if(jRadioButton_M.isSelected())
            sexe="M";
        else
            sexe="F";
        Connection con=Connexion.getConnection();
        ArrayList<Gestionnaire> tab=new ArrayList<Gestionnaire>();
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
        DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
        try{
            Statement req=con.createStatement();
            ResultSet result=req.executeQuery("SELECT * FROM gestionnaire WHERE sexegest="+" \""+sexe+"\"");
            while(result.next()){
                tab.add(gestdao.rechercher(result.getInt("idgest")));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        return tab;
    }
    private void jTextField_adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_adresseActionPerformed

    private void jRadioButton_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FActionPerformed

    private void jTextField_telKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telKeyReleased
        // TODO add your handling code here:
        if(!isNumeric(evt.getKeyChar())){
            jTextField_tel.setText(jTextField_tel.getText().replace(String.valueOf(evt.getKeyChar()),""));
        }
        
        ArrayList<Gestionnaire> tab=tel_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jTextField_telKeyReleased

    private void jTextField_adresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_adresseKeyReleased
        // TODO add your handling code here:
        ArrayList<Gestionnaire> tab=adresse_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jTextField_adresseKeyReleased

    private void jRadioButton_MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_MItemStateChanged
        // TODO add your handling code here:
        ArrayList<Gestionnaire> tab=sexe_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jRadioButton_MItemStateChanged

    private void jRadioButton_FItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_FItemStateChanged
        // TODO add your handling code here:
        ArrayList<Gestionnaire> tab=sexe_selected();
         data=new ArrayList<ArrayList<Object>>();
            for(Gestionnaire gest:tab){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+gest.getIdgest());
                ligne.add(gest.getNomgest());
                ligne.add(gest.getPrenomgest());
                ligne.add(gest.getSexe());
                ligne.add(gest.getAdressegest());
                ligne.add(gest.getTelgest());
                Button bt1=new Button("Supprimer");
                ligne.add(bt1);
                data.add(ligne);
            }
            modele.setData(data);
            tableau.setModel(modele);
            tableau.repaint();
    }//GEN-LAST:event_jRadioButton_FItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_adresse;
    private javax.swing.JCheckBox jCheckBox_nom;
    private javax.swing.JCheckBox jCheckBox_pre;
    private javax.swing.JCheckBox jCheckBox_sexe;
    private javax.swing.JCheckBox jCheckBox_tel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_F;
    private javax.swing.JRadioButton jRadioButton_M;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_adresse;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_pre;
    private javax.swing.JTextField jTextField_tel;
    private javax.swing.JTable tableau;
    // End of variables declaration//GEN-END:variables
}
