/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue.fournisseur;

import gestion.Article.Categorie;
import gestion.Article.Fournisseur;
import gestion.Authentification.AbstractDAO;
import gestion.Authentification.DAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import vue.IVue;
import vue.article.Button;
import vue.article.TModel;

/**
 *
 * @author VEK
 */
public class Modifier extends javax.swing.JFrame implements IVue{
     JTable tableau;
    /**
     * Creates new form Modif
     */
    public Modifier(ButtonModifListenerFrs bt,JTable table) {
        initComponents();
        tableau=table;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        jTextField_id.setText((String)bt.getTable().getValueAt(bt.getRow(),bt.getCol()-5)); 
        jTextField_mail.setText((String)bt.getTable().getValueAt(bt.getRow(),bt.getCol()-3));
        jTextField_nom.setText((String)bt.getTable().getValueAt(bt.getRow(),bt.getCol()-4));
        jTextField_tel.setText((String)bt.getTable().getValueAt(bt.getRow(),bt.getCol()-2));
        jTextField_adresse.setText((String)bt.getTable().getValueAt(bt.getRow(),bt.getCol()-1));
        AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY); 
        DAO<Categorie> frsdao=fac.getCategorieDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_adresse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton_annuler = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton_valider1 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modifier Fournisseur");

        jTextField_id.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("ID");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nom  *");

        jTextField_nom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nomKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Telephone  *");

        jTextField_tel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_telKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_telKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Adresse  *");

        jTextField_adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_adresseKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Mail");

        jTextField_mail.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_mail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField_mail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 51), null));
        jTextField_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_mailKeyPressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        jButton_annuler.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_annuler.setForeground(new java.awt.Color(255, 255, 255));
        jButton_annuler.setText("Annuler");
        jButton_annuler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_annuler.setContentAreaFilled(false);
        jButton_annuler.setEnabled(false);
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 0));

        jButton_valider1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_valider1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_valider1.setText("Valider");
        jButton_valider1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_valider1.setContentAreaFilled(false);
        jButton_valider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_valider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_valider1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_valider1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(jTextField_tel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_adresse, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_mail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            valider();
        }
    }//GEN-LAST:event_jTextField_nomKeyPressed

    private void jTextField_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            valider();
        }
    }//GEN-LAST:event_jTextField_telKeyPressed

    private void jTextField_adresseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_adresseKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            valider();
        }
    }//GEN-LAST:event_jTextField_adresseKeyPressed

    private void jTextField_mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            valider();
        }
    }//GEN-LAST:event_jTextField_mailKeyPressed

    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_annulerActionPerformed

    private void jButton_valider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_valider1ActionPerformed
        // TODO add your handling code here:
        valider();
    }//GEN-LAST:event_jButton_valider1ActionPerformed

    private void jTextField_telKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telKeyReleased
        // TODO add your handling code here:
        if(!isNumeric(evt.getKeyChar())){
            jTextField_tel.setText(jTextField_tel.getText().replace(String.valueOf(evt.getKeyChar()),""));
        }
    }//GEN-LAST:event_jTextField_telKeyReleased
    
    public void valider(){
        if(jTextField_nom.getText().equals("")||jTextField_adresse.getText().equals("")||jTextField_tel.getText().equals("")){
            JOptionPane opt=new JOptionPane();
            opt.showMessageDialog(null,"Veuillez remplir les champs obligatoires.\n Ces champs ont une etoile apres leur nom","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
            DAO<Fournisseur> frsdao=fac.getFournisseurDAO();
            Fournisseur frs2 = new Fournisseur(Integer.parseInt(jTextField_id.getText()),jTextField_nom.getText(),jTextField_adresse.getText(),jTextField_mail.getText(),jTextField_tel.getText());
            frsdao.modifier(frs2);
            JOptionPane opt=new JOptionPane();
            opt.showMessageDialog(null,"Fournisseur ajouté","Information",JOptionPane.INFORMATION_MESSAGE);
            ArrayList<ArrayList<Object>> data=new ArrayList<ArrayList<Object>>();
            for(Fournisseur frs:frsdao.recuperer()){
                ArrayList<Object> ligne=new ArrayList<Object>();
                ligne.add(""+frs.getIdfrs());
                ligne.add(frs.getNomfrs());
                ligne.add(frs.getMailfrs());
                ligne.add(frs.getTelfrs());
                ligne.add(frs.getAdressfrs());
                Button bt=new Button("Modifier");
                Button bt1=new Button("Supprimer");
                ligne.add(bt);
                ligne.add(bt1);
                data.add(ligne);
            }
            TableModel mod= tableau.getModel();
            TModel mod1=(TModel)mod;
            mod1.setData(data);
            tableau.repaint();
            }
    }
        @Override
    public void afficher() {
        this.setVisible(true);
    }
    
    private boolean isNumeric(char c){
        try{
            Integer.parseInt(String.valueOf(c));
        }
        catch(NumberFormatException ex){
            return false;
        }
        return true;
    }
    
    @Override
    public void cacher() {
        this.hide();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Modif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_annuler;
    private javax.swing.JButton jButton_valider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField_adresse;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_tel;
    // End of variables declaration//GEN-END:variables
}
