/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import gestion.Authentification.AbstractDAO;
import gestion.Authentification.DAO;
import gestion.Authentification.Gestionnaire;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import vue.article.Liste;
import vue.categorie.ListeCat;
import vue.compte.AdminCompte;
import vue.compte.GestionnaireCompte;
import vue.fournisseur.ListeFrs;
import vue.gestionnaire.ListeGestionnaire;

/**
 *
 * @author VEK
 */
public class VuePrincipalAdmin extends javax.swing.JFrame implements IVue {
    private Boolean Admin= false;
    private int IDgest=0;

    public void setAdmin(Boolean Admin) {
        this.Admin = Admin;
    }

    public Boolean getAdmin() {
        return Admin;
    }
    /**
     * Creates new form VuePrincipalAdmin
     */
    public VuePrincipalAdmin(boolean type,int idgest) {
        IDgest=idgest;
        Admin=type;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jPanel_princ.setLayout(new BorderLayout());
        jPanel_princ.removeAll();
        jPanel_princ.add(new Acceuil(Admin,IDgest));
        jPanel_princ.validate();
        //pour griser les boutons
         //jTabbedPane_Menu.add("debut",new OngletArticle());
        if(!Admin){
            //jButton_inventaire.setForeground(Color.GRAY);
            //jButton_inventaire.setEnabled(false);
            jButton_inventaire.setVisible(false);
            //jButton_cat.setForeground(Color.GRAY);
            //jButton_cat.setEnabled(false);
            jButton_cat.setVisible(false);
            //jButton_frs.setForeground(Color.GRAY);
            //jButton_frs.setEnabled(false);
            jButton_frs.setVisible(false);
            jButton_stat.setVisible(false);
            AbstractDAO fac = AbstractDAO.getFactory(AbstractDAO.MYSQL_DAO_FACTORY);
            DAO<Gestionnaire> gestdao=fac.getGestionnaireDAO();
            Gestionnaire gest=gestdao.rechercher(idgest);
            jLabel_nom.setText(gest.getNomgest());
            jLabel_pre.setText(gest.getPrenomgest());
        }
        else{
            jLabel_pre.setVisible(false);
            jLabel_nom.setText("Admin");
        }
        jPanel_aside.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_aside = new javax.swing.JPanel();
        jLabel_profil = new javax.swing.JLabel();
        jButton_article = new javax.swing.JButton();
        jButton_inventaire = new javax.swing.JButton();
        jButton_vente = new javax.swing.JButton();
        jButton_compte = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton_connexion = new javax.swing.JButton();
        jButton_cat = new javax.swing.JButton();
        jButton_frs = new javax.swing.JButton();
        jLabel_nom = new javax.swing.JLabel();
        jLabel_pre = new javax.swing.JLabel();
        jButton_stat = new javax.swing.JButton();
        jButton_acceuil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel_princ = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_aside.setBackground(new java.awt.Color(102, 102, 102));

        jLabel_profil.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_profil.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\couple-people-ico-png\\couple_people_icons -png\\ICON\\256x256\\brown_man.png")); // NOI18N

        jButton_article.setBackground(new java.awt.Color(153, 153, 153));
        jButton_article.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_article.setForeground(new java.awt.Color(240, 240, 240));
        jButton_article.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\construction-icons-by-mpt1st\\Construction_icons_by_mpt1st\\paint_bucket_png\\32X32.png")); // NOI18N
        jButton_article.setText(" Article");
        jButton_article.setBorder(null);
        jButton_article.setContentAreaFilled(false);
        jButton_article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_articleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_articleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_articleMouseExited(evt);
            }
        });
        jButton_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_articleActionPerformed(evt);
            }
        });

        jButton_inventaire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_inventaire.setForeground(new java.awt.Color(255, 255, 255));
        jButton_inventaire.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\brisbanetanks\\ico\\Hand-Brace-Tool.png")); // NOI18N
        jButton_inventaire.setText("  Gestionnaire");
        jButton_inventaire.setBorder(null);
        jButton_inventaire.setContentAreaFilled(false);
        jButton_inventaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_inventaireMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_inventaireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_inventaireMouseExited(evt);
            }
        });
        jButton_inventaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inventaireActionPerformed(evt);
            }
        });

        jButton_vente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_vente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_vente.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\brisbanetanks\\ico\\p.png")); // NOI18N
        jButton_vente.setText(" Vente");
        jButton_vente.setBorder(null);
        jButton_vente.setContentAreaFilled(false);
        jButton_vente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_venteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_venteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_venteMouseExited(evt);
            }
        });
        jButton_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_venteActionPerformed(evt);
            }
        });

        jButton_compte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_compte.setForeground(new java.awt.Color(255, 255, 255));
        jButton_compte.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\usericons\\User Icons\\Merchant_32.png")); // NOI18N
        jButton_compte.setText("  Mon Compte");
        jButton_compte.setBorder(null);
        jButton_compte.setContentAreaFilled(false);
        jButton_compte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_compteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_compteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_compteMouseExited(evt);
            }
        });
        jButton_compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_compteActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        jButton_connexion.setBackground(new java.awt.Color(255, 0, 0));
        jButton_connexion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_connexion.setForeground(new java.awt.Color(240, 240, 240));
        jButton_connexion.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\usericons\\User Icons\\Baby_32.png")); // NOI18N
        jButton_connexion.setText("    Deconnexion");
        jButton_connexion.setActionCommand("Deconnexion");
        jButton_connexion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_connexion.setContentAreaFilled(false);
        jButton_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_connexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_connexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton_cat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_cat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cat.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\brisbanetanks\\ico\\Manual-Drill.png")); // NOI18N
        jButton_cat.setText("   Categorie");
        jButton_cat.setContentAreaFilled(false);
        jButton_cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_catMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_catMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_catMouseExited(evt);
            }
        });
        jButton_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_catActionPerformed(evt);
            }
        });

        jButton_frs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_frs.setForeground(new java.awt.Color(255, 255, 255));
        jButton_frs.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\brisbanetanks\\ico\\Jig-Saw-Jigsaw.png")); // NOI18N
        jButton_frs.setText(" Fournisseur");
        jButton_frs.setContentAreaFilled(false);
        jButton_frs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_frsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_frsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_frsMouseExited(evt);
            }
        });
        jButton_frs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_frsActionPerformed(evt);
            }
        });

        jLabel_nom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_nom.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nom.setText("nom");

        jLabel_pre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_pre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pre.setText("prenom");

        jButton_stat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_stat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_stat.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\painting-icons-by-petalart\\ICO\\Paint-Bucket-Can.png")); // NOI18N
        jButton_stat.setText(" Statistique");
        jButton_stat.setContentAreaFilled(false);
        jButton_stat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_statMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_statMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_statMouseExited(evt);
            }
        });
        jButton_stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_statActionPerformed(evt);
            }
        });

        jButton_acceuil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_acceuil.setForeground(new java.awt.Color(255, 255, 255));
        jButton_acceuil.setIcon(new javax.swing.ImageIcon("D:\\Nouveau dossier\\java\\brisbanetanks\\ico\\Wrench.png")); // NOI18N
        jButton_acceuil.setText("Acceuil");
        jButton_acceuil.setContentAreaFilled(false);
        jButton_acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_acceuilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_acceuilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_acceuilMouseExited(evt);
            }
        });
        jButton_acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceuilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_asideLayout = new javax.swing.GroupLayout(jPanel_aside);
        jPanel_aside.setLayout(jPanel_asideLayout);
        jPanel_asideLayout.setHorizontalGroup(
            jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_asideLayout.createSequentialGroup()
                .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_asideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_cat)
                            .addGroup(jPanel_asideLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_vente)
                                    .addComponent(jButton_inventaire)
                                    .addComponent(jButton_article)))
                            .addComponent(jButton_frs)
                            .addGroup(jPanel_asideLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton_compte))
                            .addGroup(jPanel_asideLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_stat))))
                    .addGroup(jPanel_asideLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_asideLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton_acceuil))
                            .addGroup(jPanel_asideLayout.createSequentialGroup()
                                .addComponent(jLabel_profil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_nom)
                                    .addComponent(jLabel_pre))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel_asideLayout.setVerticalGroup(
            jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_asideLayout.createSequentialGroup()
                .addGroup(jPanel_asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_asideLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel_nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_pre))
                    .addGroup(jPanel_asideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton_acceuil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_article)
                .addGap(34, 34, 34)
                .addComponent(jButton_vente)
                .addGap(35, 35, 35)
                .addComponent(jButton_inventaire)
                .addGap(27, 27, 27)
                .addComponent(jButton_cat)
                .addGap(18, 18, 18)
                .addComponent(jButton_frs)
                .addGap(18, 18, 18)
                .addComponent(jButton_compte)
                .addGap(18, 18, 18)
                .addComponent(jButton_stat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_princ.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_princLayout = new javax.swing.GroupLayout(jPanel_princ);
        jPanel_princ.setLayout(jPanel_princLayout);
        jPanel_princLayout.setHorizontalGroup(
            jPanel_princLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_princLayout.setVerticalGroup(
            jPanel_princLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lanzi");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tel : 92 24 89 74");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email : Lanzi@gmail.com");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Directeur   : 65 89 45 12 / 89 45 14 78");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comptable : 89 57 25 46 / 97 21 00 33");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Secrétaire  : 98 32 10 45 / 96 56 21 00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(119, 119, 119)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(691, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_princ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel_princ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_aside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_aside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_venteActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new vue.vente.Liste(Admin,IDgest));
        jPanel_princ.validate();  
    }//GEN-LAST:event_jButton_venteActionPerformed

    private void jButton_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_articleActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new Liste(Admin,IDgest));
        jPanel_princ.validate();
    }//GEN-LAST:event_jButton_articleActionPerformed

    private void jButton_inventaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inventaireActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new ListeGestionnaire(Admin,IDgest));
        jPanel_princ.validate();
    }//GEN-LAST:event_jButton_inventaireActionPerformed

    private void jButton_articleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_articleMouseEntered
        // TODO add your handling code here:
        jButton_article.setForeground(Color.red);
    }//GEN-LAST:event_jButton_articleMouseEntered

    private void jButton_articleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_articleMouseExited
        // TODO add your handling code here:
        jButton_article.setForeground(Color.white);
    }//GEN-LAST:event_jButton_articleMouseExited

    private void jButton_venteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_venteMouseEntered
        // TODO add your handling code here:
        jButton_vente.setForeground(Color.red);
    }//GEN-LAST:event_jButton_venteMouseEntered

    private void jButton_venteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_venteMouseExited
        // TODO add your handling code here:
        jButton_vente.setForeground(Color.white);
    }//GEN-LAST:event_jButton_venteMouseExited

    private void jButton_inventaireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_inventaireMouseEntered
        // TODO add your handling code here:
        if(Admin)
            jButton_inventaire.setForeground(Color.red);
    }//GEN-LAST:event_jButton_inventaireMouseEntered

    private void jButton_inventaireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_inventaireMouseExited
        // TODO add your handling code here:
        if(Admin)
            jButton_inventaire.setForeground(Color.white);
    }//GEN-LAST:event_jButton_inventaireMouseExited

    private void jButton_compteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_compteMouseEntered
        // TODO add your handling code here:
        jButton_compte.setForeground(Color.red);
    }//GEN-LAST:event_jButton_compteMouseEntered

    private void jButton_compteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_compteMouseExited
        // TODO add your handling code here:
        jButton_compte.setForeground(Color.white);
    }//GEN-LAST:event_jButton_compteMouseExited

    private void jButton_articleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_articleMouseClicked
        // TODO add your handling code here:
        try{
            Thread.sleep(2);
            jButton_article.setForeground(Color.white);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton_articleMouseClicked

    private void jButton_venteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_venteMouseClicked
        // TODO add your handling code here:
        try{
            Thread.sleep(2);
            jButton_vente.setForeground(Color.white);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton_venteMouseClicked

    private void jButton_inventaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_inventaireMouseClicked
        // TODO add your handling code here:
        if(Admin){
            try{
            Thread.sleep(2);
            jButton_inventaire.setForeground(Color.white);
            }
            catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_jButton_inventaireMouseClicked

    private void jButton_compteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_compteMouseClicked
        // TODO add your handling code here:
        try{
            Thread.sleep(2);
            jButton_compte.setForeground(Color.white);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton_compteMouseClicked

    private void jButton_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connexionActionPerformed
        // TODO add your handling code here:
        IVue vue = new SeConnecter();
        this.hide();
        vue.afficher();
    }//GEN-LAST:event_jButton_connexionActionPerformed

    private void jButton_compteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_compteActionPerformed
        // TODO add your handling code here:
        if(Admin){
            IVue vue=new AdminCompte(Admin,IDgest);
            vue.afficher();
        }
        else{
            IVue vue=new GestionnaireCompte(Admin,IDgest);
            vue.afficher();
        }   
    }//GEN-LAST:event_jButton_compteActionPerformed

    private void jButton_catMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_catMouseClicked
        // TODO add your handling code here:
        if(Admin){
            try{
            Thread.sleep(2);
            jButton_cat.setForeground(Color.white);
            }
            catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_jButton_catMouseClicked

    private void jButton_frsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_frsMouseClicked
        // TODO add your handling code here:
        if(Admin){
            try{
            Thread.sleep(2);
            jButton_frs.setForeground(Color.white);
            }
            catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_jButton_frsMouseClicked

    private void jButton_catMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_catMouseEntered
        // TODO add your handling code here:
        if(Admin)
        jButton_cat.setForeground(Color.red);
    }//GEN-LAST:event_jButton_catMouseEntered

    private void jButton_frsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_frsMouseEntered
        // TODO add your handling code here:
        if(Admin)
        jButton_frs.setForeground(Color.red);
    }//GEN-LAST:event_jButton_frsMouseEntered

    private void jButton_catMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_catMouseExited
        // TODO add your handling code here:
        if(Admin)
        jButton_cat.setForeground(Color.white);
    }//GEN-LAST:event_jButton_catMouseExited

    private void jButton_frsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_frsMouseExited
        // TODO add your handling code here:
        if(Admin)
        jButton_frs.setForeground(Color.white);
    }//GEN-LAST:event_jButton_frsMouseExited

    private void jButton_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_catActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new ListeCat(Admin,IDgest));
        jPanel_princ.validate();
    }//GEN-LAST:event_jButton_catActionPerformed

    private void jButton_frsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_frsActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new ListeFrs(Admin,IDgest));
        jPanel_princ.validate();
    }//GEN-LAST:event_jButton_frsActionPerformed

    private void jButton_statMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_statMouseClicked
        // TODO add your handling code here:
        if(Admin){
            try{
            Thread.sleep(2);
            jButton_stat.setForeground(Color.white);
            }
            catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_jButton_statMouseClicked

    private void jButton_statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_statActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_statActionPerformed

    private void jButton_statMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_statMouseEntered
        // TODO add your handling code here:
        if(Admin)
        jButton_stat.setForeground(Color.red);
    }//GEN-LAST:event_jButton_statMouseEntered

    private void jButton_statMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_statMouseExited
        // TODO add your handling code here:
        if(Admin)
        jButton_stat.setForeground(Color.white);
    }//GEN-LAST:event_jButton_statMouseExited

    private void jButton_acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_acceuilActionPerformed
        // TODO add your handling code here:
        jPanel_princ.removeAll();
        jPanel_princ.add(new Acceuil(Admin,IDgest));
        jPanel_princ.validate();
    }//GEN-LAST:event_jButton_acceuilActionPerformed

    private void jButton_acceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_acceuilMouseClicked
        // TODO add your handling code here:
        try{
            Thread.sleep(2);
            jButton_acceuil.setForeground(Color.white);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton_acceuilMouseClicked

    private void jButton_acceuilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_acceuilMouseEntered
        // TODO add your handling code here:
        jButton_acceuil.setForeground(Color.red);
    }//GEN-LAST:event_jButton_acceuilMouseEntered

    private void jButton_acceuilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_acceuilMouseExited
        // TODO add your handling code here:
        jButton_acceuil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_acceuilMouseExited
    @Override
     public void afficher(){
        this.setVisible(true);
    }
    public void cacher(){
        this.hide();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VuePrincipalAdmin().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_acceuil;
    private javax.swing.JButton jButton_article;
    private javax.swing.JButton jButton_cat;
    private javax.swing.JButton jButton_compte;
    private javax.swing.JButton jButton_connexion;
    private javax.swing.JButton jButton_frs;
    private javax.swing.JButton jButton_inventaire;
    private javax.swing.JButton jButton_stat;
    private javax.swing.JButton jButton_vente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_nom;
    private javax.swing.JLabel jLabel_pre;
    private javax.swing.JLabel jLabel_profil;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_aside;
    private javax.swing.JPanel jPanel_princ;
    // End of variables declaration//GEN-END:variables
}
